#!/bin/bash

psql << EOF
CREATE DATABASE aggregator ENCODING 'UTF8';
CREATE USER $POSTGRES_USER WITH PASSWORD $POSTGRES_PASSWORD;
GRANT ALL PRIVILEGES ON DATABASE  aggregator TO $POSTGRES_USER;
\c aggregator
CREATE SCHEMA IF NOT EXISTS $POSTGRES_SCHEMA;
EOF